"use client";

import { ChangeEvent, useMemo, useState } from "react";
import DemoDatasetButton from "./components/DemoDatasetButton";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

type DatasetResult = { filename: string; profile: { rows: number; columns: number; column_names: string[]; missing_cells: number; duplicate_rows: number; quality_score: number }; preview: Record<string, unknown>[] };
function numberValue(row: Record<string, unknown>, key: string) { const value = Number(String(row[key] ?? "").replace(/,/g, "")); return Number.isFinite(value) ? value : 0; }
function money(value: number) { return `₹${Math.round(value).toLocaleString("en-IN")}`; }

export default function Home() {
  const [status, setStatus] = useState("Not connected"); const [dataset, setDataset] = useState<DatasetResult | null>(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  async function checkBackend() { setStatus("Checking…"); try { const response = await fetch(`${apiUrl}/health`); if (!response.ok) throw new Error("API request failed"); const data = await response.json(); setStatus(`${data.service}: ${data.status}`); } catch { setStatus("Backend unavailable — start FastAPI on port 8000."); } }
  async function profileFile(file: File) { setUploading(true); setError(""); setDataset(null); setStatus(`Profiling ${file.name}…`); try { const formData = new FormData(); formData.append("file", file); const response = await fetch(`${apiUrl}/datasets/profile`, { method: "POST", body: formData }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Dataset upload failed."); setDataset(body); setStatus("Dataset ready for analysis"); } catch (profileError) { setError(profileError instanceof Error ? profileError.message : "Dataset upload failed."); setStatus("Dataset profiling failed"); } finally { setUploading(false); } }
  async function uploadDataset(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) await profileFile(file); }
  const summary = useMemo(() => { if (!dataset) return null; const rows = dataset.preview; const revenue = rows.reduce((sum, row) => sum + numberValue(row, "Revenue"), 0); const cost = rows.reduce((sum, row) => sum + numberValue(row, "Cost"), 0); const profit = rows.reduce((sum, row) => sum + numberValue(row, "Profit"), 0); const units = rows.reduce((sum, row) => sum + numberValue(row, "Quantity"), 0); const margin = revenue ? (profit / revenue) * 100 : 0; const regions = new Map<string, number>(); rows.forEach((row) => { const region = String(row.Region ?? "Unknown"); regions.set(region, (regions.get(region) ?? 0) + numberValue(row, "Revenue")); }); const topRegion = [...regions.entries()].sort((a, b) => b[1] - a[1])[0]; return { revenue, cost, profit, units, margin, topRegion }; }, [dataset]);

  return <main style={{ maxWidth: 1180, margin: "0 auto", padding: "48px 24px" }}>
    <section style={{ padding: 40, borderRadius: 24, background: "white", boxShadow: "0 12px 40px rgba(23,32,51,.08)" }}><p style={eyebrowStyle}>AI Business Analyst</p><h1 style={{ fontSize: "clamp(42px,7vw,76px)", lineHeight: 1.02, margin: "18px 0" }}>Turn business data into intelligent decisions.</h1><p style={{ maxWidth: 700, fontSize: 19, lineHeight: 1.7, color: "#566176" }}>Upload a business dataset or launch the retail demo to profile data quality and prepare it for intelligent analysis.</p><div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 28, alignItems: "center" }}><button onClick={checkBackend} style={buttonStyle} disabled={uploading}>Check API Connection</button><label style={{ ...buttonStyle, background: "#eef2f7", color: "#172033", opacity: uploading ? .6 : 1 }}>{uploading ? "Profiling…" : "Upload CSV / XLSX"}<input type="file" accept=".csv,.xlsx" onChange={uploadDataset} disabled={uploading} style={{ display: "none" }} /></label><DemoDatasetButton onLoaded={profileFile} /><span style={{ color: "#566176" }}>{status}</span></div>{error && <p style={{ color: "#b42318", marginTop: 18 }}>{error}</p>}</section>
    {dataset && summary && <section style={{ marginTop: 20 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 }}><MetricCard label="Revenue" value={money(summary.revenue)} /><MetricCard label="Cost" value={money(summary.cost)} /><MetricCard label="Profit" value={money(summary.profit)} /><MetricCard label="Profit Margin" value={`${summary.margin.toFixed(1)}%`} /><MetricCard label="Units" value={summary.units.toLocaleString("en-IN")} /><MetricCard label="Data Quality" value={`${dataset.profile.quality_score}/100`} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 14, marginTop: 14 }}><article style={cardStyle}><div style={eyebrowStyle}>Executive finding</div><h2>{summary.topRegion ? `${summary.topRegion[0]} leads revenue` : "Revenue leader unavailable"}</h2><p style={{ color: "#667085" }}>{summary.topRegion ? `${money(summary.topRegion[1])} in the loaded preview.` : "Upload a dataset containing Region and Revenue."}</p></article><article style={cardStyle}><div style={eyebrowStyle}>Next action</div><h2>Run the AI Analyst</h2><p style={{ color: "#667085" }}>Use the unified workflow for anomalies, forecasts, drivers and recommendations.</p></article></div><article style={{ ...cardStyle, marginTop: 14, overflowX: "auto" }}><h2>Data Quality & Preview</h2><div style={{ display: "flex", gap: 20, color: "#667085", marginBottom: 18, flexWrap: "wrap" }}><span>{dataset.profile.rows} rows</span><span>{dataset.profile.columns} columns</span><span>{dataset.profile.missing_cells} missing</span><span>{dataset.profile.duplicate_rows} duplicates</span></div><table style={{ borderCollapse: "collapse", width: "100%", minWidth: 650 }}><thead><tr>{dataset.profile.column_names.map((column) => <th key={column} style={tableCellStyle}>{column}</th>)}</tr></thead><tbody>{dataset.preview.map((row, index) => <tr key={index}>{dataset.profile.column_names.map((column) => <td key={column} style={tableCellStyle}>{String(row[column] ?? "—")}</td>)}</tr>)}</tbody></table></article></section>}
    {!dataset && <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 16, marginTop: 20 }}>{[["01","Upload & Profile","Understand data quality before analysis."],["02","Analyze","Generate KPIs, trends and business metrics."],["03","Explain","Turn analytical results into clear business insights."],["04","Decide","Support decisions with recommendations and scenarios."]].map(([number,title,description]) => <article key={number} style={cardStyle}><div style={{ fontSize: 13, fontWeight: 700, color: "#718096" }}>{number}</div><h2 style={{ fontSize: 20, margin: "10px 0" }}>{title}</h2><p style={{ color: "#667085", lineHeight: 1.6, marginBottom: 0 }}>{description}</p></article>)}</section>}
  </main>;
}
function MetricCard({ label, value }: { label: string; value: string }) { return <article style={cardStyle}><div style={{ color: "#718096", fontSize: 13 }}>{label}</div><strong style={{ display: "block", fontSize: 24, marginTop: 8 }}>{value}</strong></article>; }
const buttonStyle = { border: 0, borderRadius: 12, padding: "13px 18px", background: "#172033", color: "white", cursor: "pointer", fontWeight: 700 };
const cardStyle = { background: "white", borderRadius: 18, padding: 24, border: "1px solid #e7ebf2" };
const eyebrowStyle = { margin: 0, color: "#667085", fontSize: 11, fontWeight: 800, letterSpacing: 1.2, textTransform: "uppercase" as const };
const tableCellStyle = { padding: "10px 12px", borderBottom: "1px solid #e7ebf2", textAlign: "left" as const, whiteSpace: "nowrap" as const };
